# Generated by Django 4.2.7 on 2023-11-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
