# Generated by Django 4.2.7 on 2023-11-15 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0002_delete_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseUserShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_percent', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitwise.user')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_type', models.CharField(choices=[('EQUAL', 'EQUAL'), ('EXACT', 'EXACT'), ('PERCENT', 'PERCENT')], max_length=200)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitwise.user')),
            ],
        ),
    ]
