# Generated by Django 4.2.7 on 2023-11-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0003_expenseusershare_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
