# Generated by Django 4.2.7 on 2023-11-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0004_delete_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_type', models.CharField(choices=[('EQUAL', 'EQUAL'), ('EXACT', 'EXACT'), ('PERCENT', 'PERCENT')], max_length=200)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitwise.user')),
                ('users_share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_share', to='splitwise.user')),
            ],
        ),
    ]
