# Generated by Django 4.2.7 on 2023-11-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0007_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expense_share_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
