# Generated by Django 4.2.7 on 2023-11-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0009_alter_user_expense_share_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expense_share_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
